### ISSUE TITLE
npm run serve failed

### ISSUE THREAD

**Issue by martunta** [toxicFork/react-three-renderer-example#2]
with such message. I wonder what could be at fault? What is module 'del' ?

npm run serve

```
> react-three-renderer-example@1.0.0 serve /home/martins/workspace/react-three-renderer-example
> gulp webpack-dev-server

[22:48:07] Failed to load external module babel-register
[22:48:07] Requiring external module babel-core/register
module.js:338
    throw err;
          ^
Error: Cannot find module 'del'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/martins/workspace/react-three-renderer-example/gulpfile.babel.js:31:12)
    at Module._compile (module.js:460:26)
    at loader (/home/martins/workspace/react-three-renderer-example/node_modules/babel-core/node_modules/babel-register/lib/node.js:128:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/martins/workspace/react-three-renderer-example/node_modules/babel-core/node_modules/babel-register/lib/node.js:138:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

npm ERR! Linux 4.2.0-19-generic
npm ERR! argv "/home/martins/.nvm/versions/node/v0.12.4/bin/node" "/home/martins/.nvm/versions/node/v0.12.4/bin/npm" "run" "serve"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE
npm ERR! react-three-renderer-example@1.0.0 serve: `gulp webpack-dev-server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-three-renderer-example@1.0.0 serve script 'gulp webpack-dev-server'.
npm ERR! This is most likely a problem with the react-three-renderer-example package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp webpack-dev-server
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-three-renderer-example
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/martins/workspace/react-three-renderer-example/npm-debug.log

```

build system is rather complicated for this example, unfortunately I do not immediately understand where problem might lie. I did npm install, and it worked well.

**Comment by toxicFork** [comment]
Hi @martunta, it looks like a missed dependency, I am taking a look now :)

**Comment by toxicFork** [comment]
Just tried a brand new install here but it worked, which version of npm and nodejs do you have @martunta ?

**Comment by toxicFork** [comment]
Closing after lack of response
