### ISSUE TITLE
missing module 'del'

### ISSUE THREAD

**Issue by finnigantime** [toxicFork/react-three-renderer-example#4]
After calling npm install and trying to start the webserver, I get an error that module 'del' is missing. Installing it via `npm install --save-dev del` fixes it and allows the webserver to start successfully for me.

```
$ npm run serve

> react-three-renderer-example@1.0.0 serve /private/var/admin/Documents/GitHub/react-three-renderer-example
> gulp webpack-dev-server

[10:43:54] Failed to load external module babel-register
[10:43:54] Requiring external module babel-core/register
module.js:327
    throw err;
    ^

Error: Cannot find module 'del'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (gulpfile.babel.js:8:1)
    at Module._compile (module.js:409:26)
    at loader (/private/var/admin/Documents/GitHub/react-three-renderer-example/node_modules/babel-core/node_modules/babel-register/lib/node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (/private/var/admin/Documents/GitHub/react-three-renderer-example/node_modules/babel-core/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)

npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "serve"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code ELIFECYCLE
npm ERR! react-three-renderer-example@1.0.0 serve: `gulp webpack-dev-server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-three-renderer-example@1.0.0 serve script 'gulp webpack-dev-server'.
npm ERR! This is most likely a problem with the react-three-renderer-example package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp webpack-dev-server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-three-renderer-example
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls react-three-renderer-example
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/admin/Documents/GitHub/react-three-renderer-example/npm-debug.log
```

**Comment by toxicFork** [comment]
Thanks for the report and PR :)

Which version of npm and nodejs do you have btw?

**Comment by toxicFork** [comment]
Sorry I just came back to this bug and saw that the npm versions were mentioned in the logs.

I recommend trying with npm@3.5.2 and if it's still happening please reopen the issue.
